openapi: 3.0.0
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: OpenApi Rest Article

# Paths supported by the server application
paths:

  /doers:
    get:
      operationId: ad_doers.read_all
      tags:
        - Doer
      summary: Read the entire set of doers, sorted by doer_phone
      description: Read the entire set of doers, sorted by phone numbers
      parameters:
        - name: doer_phone
          in: query
          schema:
            type: string
            pattern: '^[0-9+-]*$'
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 0
            default: 100
      responses:
        '200':
          description: Successfully read doers set operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Doer'

  '/doer/{doer_id}':
    get:
      operationId: ad_doers.read_one
      tags:
        - Doer
      summary: Show all ad_doers's ad_doers
      description: Show all the ad_doers's ad_doers
      parameters:
        - $ref: '#/components/parameters/doer_id'
      responses:
        '200':
          description: Successfully read ad_doers from ad_doers data operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doer'
        '404':
          description: Doer does not exist
    put:
      operationId: ad_doers.create
      tags:
        - Doer
      summary: Create or update the ad_doers and store his to the db
      description: Create or updatethe ad_doers and store his to the db
      parameters:
        - $ref: '#/components/parameters/doer_id'
      responses:
        '200':
          description: The ad_doers updated
        '201':
          description: The ad_doers successfuly added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doer'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-body-name: ad_doers


  /ads:
    get:
      operationId: ad_doers.read_all
      tags:
        - Ad
      summary: Read the entire set of ad_doers for all doers, sorted by date
      description: Read the entire set of ad_doers for all doers, sorted by date
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
        - name: issues
          in: query
          schema:
            type: integer
            minimum: 0
      responses:
          '200':
            description: Successfully read ad_doers for all doers operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Ad'

  /ad/{ad_id}:
    get:
      operationId: ad_doers.read_one
      tags:
        - Ad
      summary: Read the ad
      parameters:
        - $ref: '#/components/parameters/ad_id'
      responses:
        '200':
          description: The ad successfully read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
        '404':
          description: The ad not found

    put:
      operationId: ad_doers.create
      tags:
        - Ad
      summary: Create the ad and store his in the db
      parameters:
        - $ref: '#/components/parameters/ad_id'
      responses:
        '200':
          description: The ad updated
        '201':
          description: THe ad successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ad'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-body-name: ad


  /rubrics:
    get:
      operationId: rubric.read_all
      tags:
        - Rubric
      summary: Read the entire set of rubric, sorted by rubric_parent
      description: Read the entire set of rubric, sorted by rubric_parent
      responses:
        '200':
          description: Successfully read rubric set operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rubric'

  /login:
    post:
      operationId: user.login
      tags:
        - Security
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
        - $ref: '#/components/parameters/csrf'
      responses:
        '200':
          description: form showed
        '404':
          description: not found

  /logout:
    get:
      operationId: user.logout
      tags:
        - Security
      responses:
        '200':
          description: User successfully logged out
        '404':
          description: Function not found

components:
  parameters:
    username:
      name: username
      required: true
      in: body
      schema:
        type: string
        maxLength: 20
    password:
      name: password
      required: true
      in: body
      schema:
        type: string
        format: password
        maxLength: 20
    csrf:
      name: scrf
      required: true
      in: body
      schema:
        type: string
    doer_id:
      name: doer_id
      in: path
      description: Id of the smt to get
      required: true
      schema:
        type: integer
        minimum: 1
    ad_id:
      name: ad_id
      in: path
      description: Id of the smt to get
      required: true
      schema:
        type: integer
        minimum: 1
    doer:
      name: ad_doers
      in: body
      description: ad_doers to create
      required: True
      schema:
        $ref: '#/components/schemas/Doer'
    ad:
      name: ad
      in: body
      description: ad to create
      required: true
      schema:
        $ref: '#/components/schemas/Ad'

  schemas:
    Ad:
      type: object
      required:
        - ad_text
      properties:
        ad_id:
          type: integer
          description: Id of this ad
          example: 15
          readOnly: true
        ad_text:
          type: string
          description: content of this ad
          example: '1,5=2=3. 2-к. мгб. 38 кв.м по ул. Емлина, 2, высокий 1 этаж, пл. окна, сейф-дверь, косметический ремонт на 2-, 3-к., с нашей доплатой.'
        ad_rubric:
          type: integer
          description: Id of rubric this ad is associated with
          example: 4
        ad_frame:
          type: integer
          description: The flag ad may be printed in frame
          example: 1
        ad_doer:
          type: integer
          description: Id of ad_doers this ad is associated with
          example: 134
        ad_timestamp:
          type: string
          description: Create/Update date of this ad
    Doer:
      type: object
      required:
        - doer_phone
      properties:
        doer_id:
          type: integer
          description: Id of the ad_doers
          example: 1
          readOnly: true
        doer_phone:
          type: string
          description: Phone number of the ad_doers
          example: '8-922-225-65-53'
          readOnly: false
        doer_name:
          type: string
          description: Name of the ad_doers
          example: 'Галина'
          readOnly: false
    Rubric:
      type: object
      required:
        - rubric_name
      properties:
        rubric_id:
          type: integer
          description: Id of the Rubric
          example: 4
          readOnly: true
        rubric_name:
          type: string
          description: Name of rubric for Ads
          example: '1-комнатные'
        rubric_marks:
          type: string
          description: Different flags for printing
          example: '~#'
        rubric_parent:
          type:  integer
          description: The parent of rubric for building rubrics tree
          example: 1