swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:

  /user:
    get:
      operationId: user.read_all
      tags:
        - User
      summary: Read the entire set of users, sorted by user_phone
      description: Read the entire set of users, sorted by phone numbers
      responses:
        200:
          description: Successfully read users set operation
          schema:
            type: array
            items:
              properties:
                user_id:
                  type: integer
                  description: Id of the user
                user_phone:
                  type: string
                  description: Phone number of the user
#                ads:
#                  type: array
#                  items:
#                    properties:
#                      ad_id:
#                        type: integer
#                        description: Id of this ad
#                      ad_text:
#                        type: string
#                        description: content of this ad
#                      ad_rubric:
#                        type: integer
#                        description: Id of rubric this ad is associated with
#                      ad_frame:
#                        type: integer
#                        description: frame
#                      ad_owner:
#                        type: integer
#                        description: Id of user this ad is associated with
#                      ad_timestamp:
#                        type: string
#                        description: Create/Update date of this ad
    post:
      operationId: user.create
      tags:
        - User
      summary: Create the user and store his to the db
      description: Create the user and store his to the db
      parameters:
        - name: user
          in: body
          description: User to create
          required: True
          schema:
            type: object
            properties:
              user_phone:
                type: string
                description: User's number created
      responses:
        201:
          description: The user successfuly added
          schema:
            properties:
              user_id:
                type: integer
                description: Id of the user
              user_phone:
                type: string
                description: Phone number of the user

  /user/{user_id}:
    get:
      operationId: user.read_one
      tags:
        - User
      summary: Show all user's ads
      description: Show all the user's ads
      parameters:
        - name: user_id
          in: path
          description: Id of the user to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read user from user data operation
          schema:
            type: object
            properties:
              user_id:
                type: string
                description: Id of the user
              user_phone:
                type: string
                description: Phone number of the user
              ads:
                type: array
                items:
                  properties:
                    ad_id:
                      type: integer
                      description: Id of this add
                    ad_text:
                      type: string
                      description: content of this ad
                    ad_rubric:
                      type: integer
                      description: Id of rubric this ad is associated with
                    ad_frame:
                      type: integer
                      description: Flag of needs published this ad in frame
                    ad_owner:
                      type: integer
                      description: Id of user this ad is associated with
                    ad_timestamp:
                      type: string
                      description: Create/Update timestamp of this ad

  /ads:
    get:
      operationId: ads.read_all
      tags:
        - Ads
      summary: Read the entire set of ads for all users, sorted by date
      description: Read the entire set of ads for all users, sorted by date
      responses:
          200:
            description: Successfully read ads for all users operation
            schema:
              type: array
              items:
                properties:
                  ads:
                    type: array
                    items:
                      properties:
                        ad_id:
                          type: integer
                          description: Id of this ad
                        ad_text:
                          type: string
                          description: content of this ad
                        ad_rubric:
                          type: integer
                          description: Id of rubric this ad is associated with
                        ad_frame:
                          type: integer
                          description: frame
                        ad_owner:
                          type: integer
                          description: Id of user this ad is associated with
                        ad_timestamp:
                          type: string
                          description: Create/Update date of this ad

  /rubrics:
    get:
      operationId: rubric.read_all
      tags:
        - Rubrics
      summary: Read the entire set of rubric, sorted by rubric_parent
      description: Read the entire set of rubric, sorted by rubric_parent
      responses:
        200:
          description: Successfully read rubric set operation
          schema:
            type: array
            items:
              properties:
                rubric_id:
                  type: integer
                  description: Id of the rubric
                rubric_name:
                  type: string
                  description: Name of the rubric
                rubric_marks:
                  type: string
                  description: different marks for designer